
import {
    Loader2,
    Github,
    Chrome,
    ArrowRight,
    ArrowLeft,
    Sparkles,
    Layout,
    Plus,
    Edit,
    Trash,
    ArrowUp,
    ArrowDown,
    Check,
    ChartBar,
    Smartphone,
    User,
    Users,
    Eye,
    AlertCircle,
    Mail,
    EyeOff,
    Play,
    Zap,
    Menu,
    X,
    Settings,
    LogOut,
    Home,
    MessageSquare,
    FileText,
    Image,
    Database,
    Monitor,
    Save,
    Wand2,
    Copy,
    ExternalLink,
    RefreshCw,
    Download,
    Upload,
    Globe,
    Link2,
    BookOpen,
    List
} from "lucide-react";

export const Icons = {
    spinner: Loader2,
    gitHub: Github,
    google: Chrome,
    arrowRight: ArrowRight,
    arrowLeft: ArrowLeft,
    sparkles: Sparkles,
    layout: Layout,
    plus: Plus,
    edit: Edit,
    trash: Trash,
    arrowUp: ArrowUp,
    arrowDown: ArrowDown,
    check: Check,
    chart: ChartBar,
    smartphone: Smartphone,
    user: User,
    users: Users,
    eye: Eye,
    alert: AlertCircle,
    mail: Mail,
    eyeOff: EyeOff,
    play: Play,
    zap: Zap,
    menu: Menu,
    x: X,
    settings: Settings,
    logout: LogOut,
    home: Home,
    message: MessageSquare,
    file: FileText,
    image: Image,
    database: Database,
    monitor: Monitor,
    save: Save,
    wand: Wand2,
    copy: Copy,
    externalLink: ExternalLink,
    refresh: RefreshCw,
    download: Download,
    upload: Upload,
    globe: Globe,
    link: Link2,
    bookOpen: BookOpen,
    list: List
};
